### ISSUE TITLE
File won't open properly

### ISSUE THREAD

**Issue by L1lith** [Saul-Mirone/milkdown-vscode#1]
Thank you for this awesome project this is great :) I just have one issue where the following file will not open properly with milkdown.
[https://github.com/L1lith/Sandhands/blob/master/README.md](https://github.com/L1lith/Sandhands/blob/master/README.md)

Here's what it looks like to me in the editor:
![what it looks like in milkdown](https://user-images.githubusercontent.com/34887287/130305017-4f5310b1-0a87-4dee-8b55-a86158fa3a88.PNG)

Also I tried opening another file and it worked fine. I believe Milkdown for some reason doesn't like this file, it might be the HTML image tag in the beginning.

**Comment by Saul-Mirone** [comment]
That's because the html tag is not supported by millkdown, I'll implement it in next milkdown version.

**Comment by Saul-Mirone** [comment]
Fixed in 0.0.7
