### ISSUE TITLE
Random spaces added in lists

### ISSUE THREAD

**Issue by Milo123459** [Saul-Mirone/milkdown-vscode#11]
Minimal reproduction

https://user-images.githubusercontent.com/50248166/134420428-5360d285-081c-48f3-9525-8c3f5c859a31.mp4

Simple video, you can add anything from my testing and it does this.

**Comment by Saul-Mirone** [comment]
That's a expected behavior because serializer of milkdown will add the empty lines.

**Comment by Milo123459** [comment]
So this isn't a bug?

**Comment by Saul-Mirone** [comment]
No it's not

**Comment by Saul-Mirone** [comment]
Imagine it as markdown wrote by AI, it has it's own code style

**Comment by Milo123459** [comment]
I see!
