### ISSUE TITLE
使用 Milkdown 打开包含某些内容的 Markdown 文件时出现错误

### ISSUE THREAD

**Issue by LittleSound** [Saul-Mirone/milkdown-vscode#13]
我发现将 Milkdown 设置为 VSCode 的默认 Markdown 浏览器之后，打开某些 `.md` 文件时是一片空白的。
我尝试逐一排查某个文档中的内容，最终发现这段会导 Mikdown 故障的文本
``````markdown
# BUG

```service
HI~
```

``````

![image](https://user-images.githubusercontent.com/19204772/139861786-1e926ab0-a262-4c6e-b0da-1b45a7ab3d6b.png)

我又尝试了一些别的代码块，比如 `vue`，似乎任何不被支持的代码块格式都会像 `service` 一样导致 Milkdown 出现故障

**Comment by Saul-Mirone** [comment]
Received

**Comment by Saul-Mirone** [comment]
Fixed
