### ISSUE TITLE
Milkdown shortcuts conflict with built-in keybindings.

### ISSUE THREAD

**Issue by yfzhao20** [Saul-Mirone/milkdown-vscode#14]
For example, Ctrl+B conflicts with "open sidebar":
![5jfgfd](https://user-images.githubusercontent.com/80528249/144170511-4946626d-b458-4330-985e-bfdc660af8d4.gif)

Ctrl+Shift+B conflicts with "build task"
![5jfgfd](https://user-images.githubusercontent.com/80528249/144170575-63058ed8-e3f5-48b1-94b3-205631a98ed8.gif)

Maybe we can register keybinding commands to avoid that?

**Comment by Saul-Mirone** [comment]
Sure, I'll optimize it.

**Comment by Saul-Mirone** [comment]
Fixed in new version.
