### ISSUE TITLE
Cursor position lost and falls back to end of the document when saving

### ISSUE THREAD

**Issue by Win7GM** [Saul-Mirone/milkdown-vscode#17]
The cursor position is lost when saving using Ctrl+S. This causes the cursor to jump to its default position, which is end of the file, upon user input using keyboard.

It seems sometimes auto saving also causes this, but frankly speaking I cannot always reproduce it. So the cause is unknown to me.

**Comment by Saul-Mirone** [comment]
Fixed in new version.
