### ISSUE TITLE
Make the VSCode description more descriptive

### ISSUE THREAD

**Issue by L1lith** [Saul-Mirone/milkdown-vscode#3]
The current VSCode extension description is "Use milkdown in your favorite editor." compared to "Use Milkdown in your favorite editor to edit markdown.". I think this is a problem because it doesn't say that it edits Markdown files and that's going to be really confusing to people searching for a MD editor in the extension marketplace.

It's my recommendation that either the description be changed to match the repo description, or be changed to something else that makes it clear that Milkdown is for editing MD files.

Some other ideas:
- Markdown with Milkdown
- Edit Markdown with Milkdown
- Milkdown Markdown Editor
- Use Milkdown to edit Markdown

**Comment by Saul-Mirone** [comment]
Make sense, I'll take it into consider

**Comment by Saul-Mirone** [comment]
Done in 0.0.7
