### ISSUE TITLE
Request: tab and shift+tab adjust bullet/number list indentation

### ISSUE THREAD

**Issue by pbarnum** [Saul-Mirone/milkdown-vscode#36]
It would be convenient if while I am making a bulleted or numbered list to hit the `tab` or the `shift+tab` keys to adjust the indentation of the line item the cursors (or cursors) are currently on, including block highlighted lines.

**Comment by Saul-Mirone** [comment]
We have `Ctrl/Cmd-[` and `Ctrl/Cmd-]` by default, you can also remap it yourself.

**Comment by pbarnum** [comment]
Oh great, thank you for the information! I must have missed this in the docs 😅

**Comment by Charuru** [comment]
I tried to rebind it to tab but it did not work.

<img width="1655" alt="Screen Shot 2022-09-23 at 1 01 47 PM" src="https://user-images.githubusercontent.com/214436/192013912-0910a0c2-eec1-411a-b5ab-5c0f18f46d7d.png">

Any idea?

I don't want to eliminate the use of normal tabs, I just want tabs to create the child bullet when it's on a bullet.

**Comment by leeeezx** [comment]
> I tried to rebind it to tab but it did not work.
> 
> <img alt="Screen Shot 2022-09-23 at 1 01 47 PM" width="1655" src="https://user-images.githubusercontent.com/214436/192013912-0910a0c2-eec1-411a-b5ab-5c0f18f46d7d.png">
> 
> Any idea?
> 
> I don't want to eliminate the use of normal tabs, I just want tabs to create the child bullet when it's on a bullet.

you can try to edit "keybingings.json" file, 
1. find : "command": "extension.milkdown.sink",
2. edit "when" :

```json
{
  "key": "tab",
  "command": "extension.milkdown.sink",
  "when": "milkdown.active && !inDebugRepl && !suggestWidgetVisible && !editorTabMovesFocus"
}
```
