### ISSUE TITLE
Any plan to enable outline ?

### ISSUE THREAD

**Issue by ivaquero** [Saul-Mirone/milkdown-vscode#5]
Hi, this is a wonderful extension. Since outline is an import feature, any plan to enable outline ? Will this extension get an outline using VS Code's native struction or by itsself ?

**Comment by Saul-Mirone** [comment]
Do you mean a minimap on the right side?

**Comment by integzz** [comment]
The navigation panel on the left side.

![image](https://user-images.githubusercontent.com/46377665/131690761-4ac130af-b647-4840-8908-13c803b5a6b6.png)

**Comment by Saul-Mirone** [comment]
I'll try to figure out how to add it if I have time.

**Comment by Saul-Mirone** [comment]
Done
