### ISSUE TITLE
Can you please add the math and table plug-ins

### ISSUE THREAD

**Issue by fyemath** [Saul-Mirone/milkdown-vscode#6]
Thank you for the extension!
Can you please add the plug-ins for math and table to the extension?

**Comment by Saul-Mirone** [comment]
Table is already supported，math will be supported next version

**Comment by fyemath** [comment]
Awesome! Thank you! When will the next version be published?

**Comment by Saul-Mirone** [comment]
In this week I think.

**Comment by Saul-Mirone** [comment]
Finished and will be released tomorrow.

**Comment by fyemath** [comment]
> Finished and will be released tomorrow.

Great! Thank you! I will test it tomorrow.

**Comment by Saul-Mirone** [comment]
> 
> 
> > Finished and will be released tomorrow.
> 
> Great! Thank you! I will test it tomorrow.

In face, you can test it after 5 minutes, releasing.

**Comment by Saul-Mirone** [comment]
Released finished and you can try v0.0.9

**Comment by fyemath** [comment]
> Released finished and you can try v0.0.9

Awesome! It works perfectly, rendering math without any problem. Thank you!
